name: easybill_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_fonts: ^6.2.1
  flutter: 
    sdk: flutter
  dio: ^4.0.6
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  equatable: ^2.0.5
  modal_bottom_sheet: ^3.0.0
  bottom_sheet_scaffold: ^0.1.9
  flutter_staggered_grid_view: ^0.7.0
  device_info_plus: ^10.1.0
  math_expressions: ^2.5.0
  image_picker: ^1.1.1
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  blue_thermal_printer: ^1.2.3
  # flutter_blue_plus: ^1.32.7
  permission_handler: ^11.3.1
  mobile_scanner: ^5.1.1
  get_cli: ^1.8.1
  intl: ^0.18.1
  razorpay_flutter: ^1.3.7
  fluttertoast: ^8.2.6
  image: ^4.2.0
  crypto: ^3.0.3
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  audioplayers: ^6.0.0
  file_picker: ^8.0.6
  upi_payment_qrcode_generator: ^1.4.0
  thermal_printer_sdk:
    path:
      "custom-plugin/thermal_printer_sdk"

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/add_image.png
    - assets/icons/icons_lancher.png
    - assets/sounds/beep.mp3
    - assets/images/daddy_poc.png

